name: json_typedef_dart
description: JSON Validation for Dart using Json Type Definition. Implements the standard introduced at https://jsontypedef.com/
version: 0.0.3
homepage: https://github.com/thinkassembly/json_typedef_dart

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1


